---
name: Suhas
surname: Hegde
position: "Senior Data Engineer"
address: "Rakuten Rewards, San Mateo"
phone: +1 301 338 3994
email: "srhegdegadikai@gmail.com"
github: srhegdegadikai
linkedin: srhegdegadikai
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Focused on anything & everything related to data & data-systems, cloud computing & analytics. Been writing & deploying production code related to data for 3+ years in the affiliate marketing domain"
output: 
  vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Work

```{r work}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, 
  "Senior Data Engineer", "Rakuten Rewards (formerly Ebates)", "San Mateo", "Jul 2018 - Present"
) %>% 
  detailed_entries(role, dates, company, loc)

tribble(
  ~ work_details,
  "Design and implementation of cloud based Petabyte scale Data-warehouse using Snowflake, AWS & Kubernetes(EKS)",
  "Migration of batch-jobs/workloads(> 800) from a data-center to Kubernetes workloads running on AWS-EKS",
  "Implementation of Apache-Spark(distributed computing) workloads on Kubernetes using spark-operator framework",
  "AWS-Cloud cost optimization by using Spot instances for Apache-Spark production workloads on EKS",
  "Adoption of server-less computing using AWS-Lambda for data-exports to partners(from AWS -> GCP/Azure)",
  "Automation of Snowflake administrative tasks using Python-scripts & Github-actions",
  "Complete migration of all infra automation to Github-actions from Jenkins"
) %>%
  detailed_entries(why=work_details)
```


# Skills

## Programming/Scripting - 

```{r programming}
tribble(
  ~ language, 
  "Python - Batch jobs, internal APIs & scripting for infra-automation",
  "SQL - Analytics, Data-warehouse maintenance",
  "R - Analytics, reporting",
  "Shell scripting"
) %>% 
  detailed_entries(why=language)
```

## Frameworks/Services - 

```{r tech}
tribble(
  ~ tech, 
  "Kubernetes, Docker & Helm - Batch workloads using  K8s-Cronjobs and K8s-Operators(Spark-Operator & Argo-Workflows)",
  "AWS Services - EKS, EMR, ECR, Lambda etc.",
  "Snowflake - Data-warehouse storing streaming data, batch data from RDBMS and various internal/external APIs"
) %>% 
  detailed_entries(why=tech)
```


# Education

```{r education}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Science", "2018", "Frostburg State University", "Maryland, USA",
  "Bachelor of Commerce", "2016", "Karnatak University", "Dharwad, India"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

